apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:  # service 관점에서 생각하기
    - targetPort: 80  # 미입력시 port와 같은 포트로 간주됨
      port: 80
      nodePort: 30008  # 미입력시 30_000 ~ 32_767
  selector:
    app: myapp
    type: front-end
